### ISSUE TITLE
Does this also include zotero pdf reader?

### ISSUE THREAD

**Issue by Archie-2021** [Rosmaninho/Zotero-Dark-Theme#12]
If not it would be nice to be added to it

**Comment by Rosmaninho** [comment]
When the version with the pdf reader is launched I'll look into it. It's not easy though.
I alreaady themed the tabs, but not the PDF reader.

**Comment by taro-ball** [comment]
@Svnipni  try Foxit pdf reader, they have an amazing dark skin in the latest version (11.1), and it's totally free

**Comment by Svnipni** [comment]
Yeah very true. I've been using Foxit for a while but had to downgrade
since it lost its darkmode with 11. Glad to hear it's returned in 11.1 :)
I still kind of hope zotero's pdf reader can be given a dark mode. I
couldn't quite get the hang of foxit opening in files in tabs or separate
windows

**Comment by Rosmaninho** [comment]
I don't use the Beta version because it is unstable and I am now avoiding to look into that. I just had free time a few months ago to start looking into it so I decided to get some work done already. I checked the PDF reader but when I got there, I didn't have the time to try to theme it already. I'm not even sure if it's possible.

I think that when the Zotero devs get around to it they'll add a dark theme. They can even use my .css to save time.
Besides Foxit, I would recommend PDF XChange Editor. It also has a lot of personalization and I use it with a dark theme. Another alternative to quickly read PDFs  is to install Quicklook on Windows to open pdfs just by pressing the space bar.

**Comment by Rosmaninho** [comment]
I themed what I could in the PDF reader. Everything else is not themeable via a userChrome.css stylesheet unfortunately. I'll close this issue but if someone manages to theme the PDF reader with a userChrome.css file please re-open this.
