### ISSUE TITLE
Unreadable color combination when a collection is highlighted

### ISSUE THREAD

**Issue by Galileji** [Rosmaninho/Zotero-Dark-Theme#16]
When an article is selected, and Ctrl is pressed, the collection in which the article is present is highlighted in yellow. However the name of the collection remains white, and white on yellow background is not very readable.
![image_37](https://user-images.githubusercontent.com/63428646/141643162-1fb919d6-62df-4da1-a438-e8a3dcaa8b4e.png)
k.

Thank you so much for this beautiful work.

**Comment by Ak5cel** [comment]
Same on mine, version 5.0.96.3

> Weird, I can't replicate this.
What version of Zotero is this?

Steps to replicate:

1. Add the same item to multiple collections
2. Click on the item in one collection and press Ctrl, all the other collections the item is in would be highlighted

It can be found in the support docs [here](https://www.zotero.org/support/collections_and_tags#identifying_collections_an_item_is_in).

**Comment by Galileji** [comment]
Thanks @Ak5cel for the explanation. This can also be replicated like this
- adding an item to a collection
- select My Library on the left menu
- click that item
- press Ctrl

I'm using verison 5.0.96.3 of Zotero

**Comment by Rosmaninho** [comment]
Thanks! I managed to replicate it like this. Man, there are some truly edge cases. 
It's good you caught this in 5.0.96.3. 
The next version will break a lot of stuff because the Zotero devs are re-writing a lot of the code so I don't want to tackle it before a final release version since a lot might change before then. I will merge the pull request.

**Comment by Galileji** [comment]
Thank you so much @Rosmaninho. Very cool name btw!
