### ISSUE TITLE
Hardly readable text

### ISSUE THREAD

**Issue by Galileji** [Rosmaninho/Zotero-Dark-Theme#22]
In the Info pane, two elements are hardly readable, because they have black text on grey background. They are:
- Citation Key
- Item Type, but only when the mouse is hovering over it

![Immagine 2022-01-07 135059](https://user-images.githubusercontent.com/63428646/148546518-1add286a-1511-428f-92e7-4a629ca6f38a.png)

**Comment by Rosmaninho** [comment]
Weird. I had that fixed in my side.
What Zotero version are you using?

**Comment by Galileji** [comment]
I'm using Zotero 5.0.96.3, and the current version of the dark theme. 
Anyway it's not a big deal, I just wanted to let you know ;)

**Comment by Rosmaninho** [comment]
The weird thing is that when you hover over those elements there should be a light blue box highlighting those fields.
It's weird you don't get that one, because I didn't do anything to remove it.

Anyway, go to line 162:
/*Change color of fields in item pane (clicky items) when hovering */
#zotero-item-pane-content .zotero-clicky:hover
{	color: black !important;
  border-radius: 0px !important; }

Change color: black !important to color:white !important
That should fix your issue.

**Comment by Galileji** [comment]
Yes, thank you so much; this did fix the problem with "Item Type", even though "Citation Key" remains black, as that is not a problem concerning hovering.
