### ISSUE TITLE
update for zotero 6.0

### ISSUE THREAD

**Issue by Geo123abc** [Rosmaninho/Zotero-Dark-Theme#25]
Thanks for your great work. As we all know, zotero has been update to version 6.0 ([6.0 changelog [Zotero Documentation]](  https://www.zotero.org/support/6.0_changelog  )    ), is there any plan to update the dark theme?

**Comment by Rosmaninho** [comment]
I won't support Beta builds besides what I already launched. I only support the release version, because the Betas change stuff often and it's a nightmare to keep up with it.
When there's a new stable release I will support it. But I welcome anyone to sift through the code and to theme elements that might break in Beta builds.

**Comment by jrissman** [comment]
[Zotero 6 was officially released today](https://www.zotero.org/support/changelog#changes_in_60_march_17_2022) (March 17, 2022).  Unfortunately, it does look like this unofficial dark theme will need some updates to maintain compatibility.  The left-hand panel no longer is dark, and items that are selected or being moused over can't be read because the white text is too close to the light blue highlight color.  Also, the note editor is no longer dark (i.e. the instructions from 10cks in the README no longer work).  I really value this dark theme for Zotero and hope the updates to make it work with Zotero 6 will be quick and easy.

**Comment by PHJT003** [comment]
Thanks for the awesome dark theme, @Rosmaninho!
Does anybody know how to revert to the default theme after Zotero's update to version 6.0?
I don't seem to find the CSS file in the path anymore...
Thanks,
V

**Comment by PHJT003** [comment]
> Thanks for the awesome dark theme, @Rosmaninho! Does anybody know how to revert to the default theme after Zotero's update to version 6.0? I don't seem to find the CSS file in the path anymore... Thanks, V

I think there was a problem with my machine: first, I had to clean the registry and restart Zotero, as well as the computer.
After doing this, I could find the `chrome\userChrome.css` file and could delete the whole folder.
This process restored Zotero's default theme.

Apologies for the redundant post - I hope it could help other users who might be stuck as I was, though.

Best,
Valerio

**Comment by TheAndyChow** [comment]
Here's a quick fix until there's an update:

1. Uncomment lines 38 - 43.
2. Replace line 42 with `filter: brightness(75%);`
3. Change the color value on line 43 from `white` to `black`.
4. Change the selector on line 54 from `treechildren` to `#zotero-collections-tree`.
5. Uncomment lines 58 - 99.
6. Uncomment lines 147 - 155.
