### ISSUE TITLE
PR suggestion

### ISSUE THREAD

**Issue by alanlivio** [Rosmaninho/Zotero-Dark-Theme#5]
There is an open issue in Zotero github. Your theme (with a Zotero settings button) will be a good PR.
   https://github.com/zotero/zotero/issues/1683

**Comment by Rosmaninho** [comment]
I would love if they shipped my dark theme by default. But it only supports Windows currently.

**Comment by MalcolmMielle** [comment]
Just for information but zotero is naturally dark on my linux machine. The theme is only needed on Windows. SO if you ant to push this on the official branch you could just ignore Linux

![Screenshot from 2021-04-26 21-27-20](https://user-images.githubusercontent.com/4457840/116139348-38239400-a6d6-11eb-81ed-9355bc434ef1.png)

**Comment by Rosmaninho** [comment]
I didn't know that! That's great. So that means I probably would just need to focus on making a Mac theme. :)
If Zotero devs wish they can use my Dark theme. It's a Proton based theme. But many of my personal color choices are easily themeable and if they don't wish to theme the Preferences Dialog it's quite easy to deactivate it..

**Comment by hkocabas** [comment]
Not every linux distro make the Zotero app dark by default as @MalcolmMielle  mentioned though. So, I am using Debian 12 XFCE and this theme helped to make it dark since I could not find any preference option to make it dark. However, the top side bar acted weird and is still white with white text as well. So it make things hard to see there.

![Screenshot_2023-10-06_10-21-15](https://github.com/Rosmaninho/Zotero-Dark-Theme/assets/27592143/729671eb-3527-48b9-a630-e063cecb2522)
