### ISSUE TITLE
Zotero 5.0.97-beta.43 broke the CSS

### ISSUE THREAD

**Issue by jorjio** [Rosmaninho/Zotero-Dark-Theme#9]
Hi!
The new beta.43 broke the CSS dark background.
appreciate if you can help!

Thanks!

**Comment by Rosmaninho** [comment]
Hey, I don't use Beta builds so I'll wait for it to be pushed to the release channel and then try to fix it.
Could you maybe open an issue with them to know what they might've changed? That will help me fix it faster.

**Comment by jorjio** [comment]
Done
https://forums.zotero.org/discussion/comment/387906#Comment_387906

thanks!

**Comment by Rosmaninho** [comment]
Thanks! If possible open an issue in Zotero's Github as well. They answer faster there. :)

**Comment by Rosmaninho** [comment]
I checked how it looked in the portable version of the Beta and it broke a lot of it. :(

**Comment by Rosmaninho** [comment]
Already fixed most of it. However, I can't make the row spacing in the collections and items tree 30px again. What a pain.
That's the last thing missing.

**Comment by Rosmaninho** [comment]
Already committed the changes.
The fixes for 5.0.97 are grayed out by /* */ .
Remove those and the css will be fixed. 

I didn't theme the built-in pdf reader because it is still new. I also can't change row spacing because the Zotero devs removed that functionality in the new react code and I can't find a work-around. :/ I opened a topic about it in the Zotero forums, so I would ask for you guys to also reply there asking for a way to adjust density.

**Comment by Rosmaninho** [comment]
Ok, found a work-around but still not something that involves the userChrome.css file. It's this:
use 7zip to open zotero.jar and from virtualized-table.js in zotero\chrome\content\zotero\components\ change const DEFAULT_ROW_HEIGHT = 20; // px to 30
